name: fpm build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: bluikko/centos7-go@master
      with:
        build_opts: 'linux'
    - run: ls -latr
    - run: ls -latr DIST
    - name: Package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: 'make linux'
        fpm_opts: '--debug -n birdwatcher -v "2.2.1" -t rpm -s dir -C DIST/ --config-files /etc/birdwatcher/birdwatcher.conf opt/ etc/'
    - run: mv *.rpm RPMS
