name: fpm build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make 
    - name: Package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: 'make rpm'
        fpm_opts: ';'
